In [3]:
import numpy as np

In [5]:
# Creating NumPy Arrays - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2).shape)

# 2D Arrays - Matrix
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr3, arr3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <attribute 'shape' of 'numpy.ndarray' objects>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
