In [2]:
import numpy as np

In [5]:
# Creating Arrays
arr1 = np.zeros((3, 4)) #pre-filled with 0's
print(arr1, arr1.shape)

arr2 = np.ones((3, )) #pre-filled with 1's
print(arr2, arr2.shape)

arr3 = np.full((2, 3), 5) #pre-filled with a num
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1, 20, 2) #elements in range
print(arr5, arr5.shape)

arr6 = np.linspace(0, 10, 5) #evenly spaced array
print(arr6, arr6.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[1. 1. 1.] (3,)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  3  5  7  9 11 13 15 17 19] (10,)
[ 0.   2.5  5.   7.5 10. ] (5,)
