In [1]:
import numpy as np

In [2]:
# Reshaping
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

reshaped = arr.reshape((2, 3))
print(reshaped, reshaped.shape)

flattened = reshaped.flatten() #converts 2D => 1D
print(flattened, flattened.shape)

(6,)
[[1 2 3]
 [4 5 6]] (2, 3)
[1 2 3 4 5 6] (6,)


In [3]:
# Indexing
arr = np.array([1, 2, 3, 4, 5]) #1D array
print(arr[0])

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) #2D array
print(arr[0][1]) #2
print(arr[1][2]) #6

#Fancy indexing
arr = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 4]
print(arr[idx])

#Boolean indexing
print(arr[arr > 2]) #nums greater than 2
print(arr[arr % 2 == 0]) #even nums

1
2
6
[1 2 5]
[3 4 5]
[2 4]


In [4]:
# Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:6]) #[3, 4, 5, 6]
print(arr[:6]) #[1, 2, 3, 4, 5, 6]
print(arr[3:]) #[4, 5, 6, 7]
print(arr[::2]) #[1, 3, 5, 7]

[3 4 5 6]
[1 2 3 4 5 6]
[4 5 6 7]
[1 3 5 7]
