In [3]:
import numpy as np

In [4]:
# Vectorization & Broadcasting

#Vectorization
arr = np.array([1, 2, 3, 4, 5])

sq_arr = arr ** 2       #square of all nums
print(sq_arr)

arr2 = np.array([6, 7, 8, 9, 10])
print(arr + arr2)      #sum of 2 arrays

#Broadcasting
arr_mul10 = arr * 10    #multiply by 10 to all nums
print(arr_mul10)

arr1D = np.array([1, 2, 3])
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1D + arr2D)

[ 1  4  9 16 25]
[ 7  9 11 13 15]
[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]
